version: 2
updates:
  - package-ecosystem: npm
    directory: /
    assignees:
      - mcmillan
    schedule:
      interval: daily
  - package-ecosystem: github-actions
    directory: /
    assignees:
      - mcmillan
    schedule:
      interval: daily
