#!/bin/bash

set -eo pipefail

[ -z $AWS_PROFILE ] && (echo "Provide an AWS_PROFILE, please!" && exit 1)
git diff-index --quiet HEAD || (echo "Commit your work, please!" && exit 1)

set -u

npm run build
cd dist
aws s3 sync . s3://joshmcmillan.com --acl public-read
