name: Deploy
on:
  push:
    branches: main
concurrency:
  group: deploy
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
      - run: |
          corepack enable pnpm
          corepack install
          pnpm install --frozen-lockfile --strict-peer-dependencies
      - run: pnpm build
      - uses: tailscale/github-action@v3
        with:
          oauth-client-id: ${{ secrets.TAILSCALE_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TAILSCALE_OAUTH_SECRET }}
          tags: tag:zoidberg-deploy
      - uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}
          log-public-key: false
      - run: |
          ssh-keyscan zoidberg >> ~/.ssh/known_hosts
          rsync -avz --delete ./dist/ deploy@zoidberg:/var/www/joshmcmillan.com
